// Generated by scripts/chain_defaults/generate.js -- do not edit.

/// Default chain endpoint tables. Generated -- do not edit.
enum DefaultChains {
    /// Default prover URLs for supported chains.
    static func defaultProvers(for chainId: UInt64) -> [String] {
        switch chainId {
        case 1:
            return [
                "https://mainnet.colibri-proof.tech",
                "https://mainnet1.colibri-proof.tech",
                "https://mainnet-prover.incubed.net",
                "https://mainnet.colimind.com",
            ]
        case 11155111:
            return [
                "https://sepolia.colibri-proof.tech",
                "https://sepolia1.colibri-proof.tech",
                "https://sepolia.colimind.com",
            ]
        case 100:
            return [
                "https://gnosis.colibri-proof.tech",
                "https://gnosis1.colibri-proof.tech",
                "https://gnosis.colimind.com",
            ]
        case 10200:
            return ["https://chiado.colibri-proof.tech"]
        case 7091047534:
            return ["https://plataberget.colibri-proof.tech"]
        default:
            return ["https://c4.incubed.net"]
        }
    }

    /// Default Ethereum RPC URLs for supported chains.
    static func defaultEthRpcs(for chainId: UInt64) -> [String] {
        switch chainId {
        case 1:
            return [
                "https://mainnet.colibri-proof.tech/execution",
                "https://eth.drpc.org",
                "https://ethereum-rpc.publicnode.com",
                "https://singapore.rpc.blxrbdn.com",
            ]
        case 11155111:
            return [
                "https://sepolia.colibri-proof.tech/execution",
                "https://ethereum-sepolia-rpc.publicnode.com",
                "https://sepolia.gateway.tenderly.co",
            ]
        case 100:
            return [
                "https://gnosis.colibri-proof.tech/execution",
                "https://rpc.gnosischain.com",
                "https://rpc.gnosis.gateway.fm",
                "https://gnosis-rpc.publicnode.com",
            ]
        case 10200:
            return [
                "https://rpc.chiado.gnosis.gateway.fm",
                "https://rpc.chiadochain.net",
                "https://gnosis-chiado-rpc.publicnode.com",
            ]
        case 7091047534:
            return [
                "https://plataberget.colibri-proof.tech/execution",
                "https://rpc.glamsterdam-devnet-8.ethpandaops.io/",
            ]
        default:
            return []
        }
    }

    /// Default beacon API URLs for supported chains.
    static func defaultBeaconApis(for chainId: UInt64) -> [String] {
        switch chainId {
        case 1:
            return [
                "https://mainnet.colibri-proof.tech/consensus",
                "https://gateway.tenderly.co/public/mainnet",
                "https://ethereum-beacon-api.publicnode.com",
            ]
        case 11155111:
            return [
                "https://sepolia.colibri-proof.tech/consensus",
                "https://ethereum-sepolia-beacon-api.publicnode.com",
            ]
        case 100:
            return [
                "https://gnosis.colibri-proof.tech/consensus",
                "https://rpc-gbc.gnosischain.com",
                "https://gnosis-beacon-api.publicnode.com",
            ]
        case 10200:
            return ["https://rpc-gbc.chiadochain.net"]
        case 7091047534:
            return [
                "https://plataberget.colibri-proof.tech/consensus",
                "https://beacon.glamsterdam-devnet-8.ethpandaops.io/",
            ]
        default:
            return []
        }
    }

    /// Default checkpointz URLs for supported chains.
    static func defaultCheckpointz(for chainId: UInt64) -> [String] {
        switch chainId {
        case 1:
            return [
                "https://sync-mainnet.beaconcha.in",
                "https://mainnet.checkpoint.sigp.io",
                "https://mainnet-checkpoint-sync.attestant.io",
                "https://beaconstate-mainnet.chainsafe.io",
                "https://mainnet-checkpoint-sync.stakely.io",
                "https://checkpointz.pietjepuk.net",
                "https://beaconstate.ethstaker.cc",
            ]
        case 11155111:
            return [
                "https://checkpoint-sync.sepolia.ethpandaops.io",
                "https://beaconstate-sepolia.chainsafe.io",
            ]
        case 100:
            return ["https://checkpoint.gnosischain.com"]
        case 10200:
            return ["https://checkpoint.chiadochain.net"]
        case 7091047534:
            return ["https://checkpoint-sync.glamsterdam-devnet-8.ethpandaops.io"]
        default:
            return []
        }
    }

}
